name: CStyler
version: 0.1.0.0
copyright: 2019 Yan Frimmel
maintainer: yanfrimmel1411@gmail.com
author: Yan Frimmel
github: yanfrimmel/CStyler
license: MIT

extra-source-files:
- README.md

dependencies:
- hspec
- base >= 4.7 && < 5
- directory


library:
  source-dirs: src

executables:
  cstyler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CStyler

tests:
  cstyler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CStyler

description: Please see the README on GitHub at <https://github.com/yanfrimmel/CStyler#readme>
